### ISSUE TITLE
[BGT Station] "Go Back" button does not work with direct Vault navigation

### ISSUE THREAD

**Issue by larrythecucumber321** [berachain/monobera#115]
## Bug Description
When navigating to a specific Vault deposit page, the "Go Back" button does nothing because it's simply trying to invoke `history.back()`

e.g.  https://bartio.station.berachain.com/gauge/0x1c21c4e2b54f289762a6f7e8ac47f4d0c8a34351

## Expected Behavior
When there is no browser history on a Vault's page, it should instead navigate to the main page - https://bartio.station.berachain.com/gauge

**Comment by BrownBrownBear** [comment]
Fixed in https://github.com/berachain/monobera/pull/149
