### ISSUE TITLE
[BEX/BGT Station] 404 Error when depositing to Vault from BEX 

### ISSUE THREAD

**Issue by larrythecucumber321** [berachain/monobera#116]
## Bug Description 

When trying to direct to deposit BEX receipt tokens, it gives a 404 error, e.g. https://bartio.bex.berachain.com/pool/0xa51afaf359d044f8e56fe74b9575f23142cd4b76

![image](https://github.com/user-attachments/assets/1311c847-71ce-4b66-b269-c9f2ca3aaba8)

![image](https://github.com/user-attachments/assets/284d537a-eede-4195-aaf2-939888a0b274)

**Comment by BrownBrownBear** [comment]
Fixed in https://github.com/berachain/monobera/pull/149
