### ISSUE TITLE
[BEX] My Pools page prompts users to deposit in non-existent vaults

### ISSUE THREAD

**Issue by larrythecucumber321** [berachain/monobera#122]
## Bug Description
When users have provided liquidity in a pool, the pool shows up in [user pools](https://bartio.bex.berachain.com/pools?pool=userPools)

Clicking on Deposit where a vault doesn't exist for that pool results in a 404 error

![image](https://github.com/user-attachments/assets/38750851-062a-4312-895d-bd1617adb5f2)
<img width="608" alt="image" src="https://github.com/user-attachments/assets/377f8861-ea40-4462-8302-6960722cb467">

For reference, the dead link is [here](https://bartio.station.berachain.com/gauge/0x1c21c4e2b54f289762a6f7e8ac47f4d0c8a34351)

## Expected Behavior
BEX pools which do not have correspoding vaults should not have the "Deposit" option enabled beside it.

**Comment by BrownBrownBear** [comment]
Fixed in https://github.com/berachain/monobera/pull/149
