### ISSUE TITLE
[HONEY] 90d Supply chart not loading 

### ISSUE THREAD

**Issue by larrythecucumber321** [berachain/monobera#123]
## Bug Description
On the [Honey Stats](https://bartio.honey.berachain.com/#stats), the 90d Supply chart does not load and continues to spin

This is experienced on both Chrome and Firefox 
![image](https://github.com/user-attachments/assets/5903c913-835e-4379-a393-d8f0dc7f6a91)

## Expected Behavior
The 90d Supply chart renders properly

**Comment by BrownBrownBear** [comment]
Fixed here https://github.com/berachain/monobera/pull/150
