### ISSUE TITLE
[BGT Station] Delegation not queuing and missing delegations after 100 and above validators delegated (Critical Issue)

### ISSUE THREAD

**Issue by prodigyX-BeraBeraBaby** [berachain/monobera#131]
Description:
This is a very hard to replicate bug. you need to have above 100 Validators delegated only then you will be able to replicate this issue. What happens here are:

1. the user may loose a BGT on previously delegated validator
2. there are certain validators that no matter how hard you try your delegation will just be gone (this can be random per user its not always fixed
3. this is random validator for every user, but the validator that is not working for a specific user will be persistent

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/67b0b092-a0bf-493a-a5bb-73b16d6fe8d6">

Steps to replicate:
1. delegate to all validators at any amount, try to do it page by page until you reach 100 +
2. after 100 ++ you will notice some of your previously delegated validator will jsut loose a BGT delegation -> 0
3. those that suddenly become 0 if you try to delegate to them.. it will succeed but delegation will still be 0 and will not even appear on queue or user queued

Discord Reference:
https://discord.com/channels/924442927399313448/1270220521505685504/1270220521505685504

**Comment by bearpong** [comment]
hey @prodigyX-BeraBeraBaby can you provide me with a wallet address that's got more than 100 delegations?

**Comment by BrownBrownBear** [comment]
Fixed in https://github.com/berachain/monobera/pull/142

**Comment by prodigyX-BeraBeraBaby** [comment]
@bearpong  do you still need a wallet adddress?

**Comment by prodigyX-BeraBeraBaby** [comment]
I can see it here
<img width="681" alt="image" src="https://github.com/user-attachments/assets/f3c3c184-5353-477b-90d8-ac28edd2dc49">

but not here (for queued)
<img width="853" alt="image" src="https://github.com/user-attachments/assets/b5c1f271-6ff3-4942-8c8f-94fc03a2c968">

later I will update if it really delegated successfully
@BrownBrownBear
