### ISSUE TITLE
[BGT Station / Loaders] No Images

### ISSUE THREAD

**Issue by prodigyX-BeraBeraBaby** [berachain/monobera#134]
**Description:**

No Images on the following
https://bartio.station.berachain.com/redeem
<img width="523" alt="image" src="https://github.com/user-attachments/assets/890db68b-2c46-493b-965d-c539fa6938e2">

https://bartio.station.berachain.com/rewards
<img width="1448" alt="image" src="https://github.com/user-attachments/assets/f61eda82-885e-4379-b36e-c08f639c1813">

https://bartio.station.berachain.com/delegate
<img width="577" alt="image" src="https://github.com/user-attachments/assets/fe750935-d5a7-4ad6-95ac-24efbd0380af">
<img width="561" alt="image" src="https://github.com/user-attachments/assets/a5e6d631-d18f-4279-85fd-79043239d24d">

https://bartio.station.berachain.com/gauge
<img width="347" alt="image" src="https://github.com/user-attachments/assets/d7d63e1f-0a9a-4198-809d-b251b8e8fdba">

Loaders
<img width="419" alt="image" src="https://github.com/user-attachments/assets/1ddc356d-2e2b-4339-9bc1-211f7981b4c2">

**Comment by BrownBrownBear** [comment]
Fixed in https://github.com/berachain/monobera/pull/148
